#!/usr/bin/env python3
import string, random, sys


if len(sys.argv) > 1: length = int(sys.argv[1])
else: length = 32

keyspace = string.ascii_lowercase
keyspace += string.ascii_uppercase
keyspace += string.digits
keyspace += string.punctuation

key = ''
for i in range(length):
    key += random.choice(keyspace)

print(key)
